### ISSUE TITLE
Specify artwork license

### ISSUE THREAD

**Issue by picsi** [AsteroidOS/asteroid#7]
(This is probably not the correct repo for this but I couldn't find a more appropriate one)

Please specify publicly the license for artwork in the project. The logo and screenshots at https://asteroidos.org/screenshots/ for instance.

**Comment by FlorentRevest** [comment]
Fixed on https://asteroidos.org/screenshots and https://asteroidos.org/wiki/licenses/

**Comment by TheLastProject** [comment]
@FlorentRevest You forgot to specify a version of CC BY and CC BY SA

**Comment by FlorentRevest** [comment]
@TheLastProject thanks for noticing, it's fixed.
